#!/bin/sh

# start mysql server
/usr/bin/mysqld_safe &

mkdir www

cd www

git clone https://github.com/metapolator/metapolator

cd metapolator

dir=`find . -name requirements.txt | sed 's/requirements.txt$//'`

if [ -z "$dir" ]; then
        echo "No requirements.txt"
        exit 1
fi

cd $dir

pip install -r requirements.txt
mysql --user=root -e 'drop database if exists metapolatordev; create database metapolatordev;'
python metapolator/models.py