#!/bin/sh
mkdir www && cd www
git clone https://github.com/metapolator/metapolator

cd metapolator
virtualenv .venv && source .venv/bin/activate

dir=`find . -name requirements.txt | sed 's/requirements.txt$//'`

if [ -z "$dir" ]; then
        echo "No requirements.txt"
        exit 1
fi

cd $dir

pip install -r requirements.txt