#!/usr/bin/env node

// metapolator command line interface

"use strict";

var path = require('path');
var helmsman = require('helmsman');

var name = path.basename(process.argv[1], '.js');
var cli = helmsman({localDir: __dirname + '/app/commands'});
cli.on('--help', function(){
    console.log('Usage: ' + name + ' [options] [command]');
});
cli.parse();
