#!/bin/sh
sysctl vm.overcommit_memory=1

/usr/bin/mysqld_safe &
sleep 5s

if [ ! -f /home/user ]; then
    SSH_USERPASS=`pwgen -c -n -1 8`

    mkdir /home/user
    useradd -G sudo -d /home/user -s /bin/bash user
    chown user /home/user
    echo user:$SSH_USERPASS | chpasswd

    METAPOLATOR_PASSWORD=`pwgen -c -n -1 12`

    # Start mysql server
    mysqladmin -u root password $METAPOLATOR_PASSWORD
    mysql -uroot -p$METAPOLATOR_PASSWORD -e "CREATE DATABASE metapolator;"

    echo """DATABASE_USER='root'
DATABASE_PWD='$METAPOLATOR_PASSWORD'
DATABASE_NAME='metapolator'""" > /var/www/metapolator/metapolator/localconfig.py
    cp /var/www/metapolator/metapolator/localconfig.py /var/www/

    cat /var/www/metapolator/metapolator/localconfig.py

    pip install -r /var/www/metapolator/requirements.txt

    python /var/www/metapolator/metapolator/models.py
    chown -R user:user /var/www/metapolator
    
    cd /var/www/metapolator;
    ./node_modules/.bin/npm install
    ./node_modules/.bin/bower install

    echo ssh user password: $SSH_USERPASS
    echo mysql root password: $METAPOLATOR_PASSWORD
fi

supervisord -n
