#!/bin/sh
set -e

mkdir -p /var/www && cd /var/www

app=`find . -name 'run.py' | head -n 1`

if [ -z "$app" ]; then
    git clone https://github.com/metapolator/metapolator
    cd metapolator
    pip install -r requirements.txt
    cd ..
fi

cd metapolator

if [ ! -f metapolator/localconfig.py ]; then
    METAPOLATOR_PASSWORD=`pwgen -c -n -1 12`
    echo mysql root password: $METAPOLATOR_PASSWORD

    # Start mysql server
    /usr/bin/mysqld_safe &
    mysqladmin -u root password $METAPOLATOR_PASSWORD
    mysql -uroot -p$METAPOLATOR_PASSWORD -e "CREATE DATABASE metapolator;"

    echo """DATABASE_USER='root'
DATABASE_PWD='$METAPOLATOR_PASSWORD'
DATABASE_NAME='metapolator'""" > metapolator/localconfig.py

    python metapolator/models.py

    killall mysqld
    sleep 10s
fi

supervisord -n