#!/usr/bin/env node

"use strict";

exports.command = {
    description: 'run a comma-separated list of selectors on the given master'
  , arguments: '<master> <selectors>'
};

var path = require('path');
var requirejs = require('requirejs');
require('rootpath')();
requirejs.config(require('config'));

if (require.main === module) {
    requirejs([
        'commander'
      , 'ufojs/tools/io/staticNodeJS'
      , 'metapolator/project/MetapolatorProject'
    ], function (
        program
      , io
      , MetapolatorProject
    ) {
        var CommandLineError = errors.CommandLine;

        program._name = path.basename(process.argv[1], '.js').replace('-', ' ');
        program.arguments(exports.command.arguments);
        program.action(function(masterName, selectors) {
            var project = new MetapolatorProject(io);
            project.load();
            var controller = project.open(masterName);

            console.log('selectors:', selectors );

            var result = controller.queryAll(selectors);
            console.log('result:')
            console.log(result.map(function(item){ return item +' '+item.particulars }).join(',\n'));
            console.log('_______________');
          });
        program.parse(process.argv);
    }
)}
