#!/bin/sh
__hash_bang_trick=/* exec /usr/bin/env node --harmony "$0" "$@"  # -*- mode: javascript; -*- */undefined

"use strict";

exports.command = {
    description: 'interpolate a comma-separated list of masters according to a CPS expression'
  , arguments: '<masters> <interpolators>'
};

var path = require('path');
var requirejs = require('requirejs');
require('rootpath')();
requirejs.config(require('config'));

if (require.main === module) {
    requirejs([
        'commander'
      , 'metapolator/parseArgs'
      , 'ufojs/tools/io/staticNodeJS'
      , 'metapolator/project/MetapolatorProject'
      , 'metapolator/models/CPS/parsing/parseRules'
      , 'metapolator/models/CPS/Registry'
    ], function (
        program
      , parseArgs
      , io
      , MetapolatorProject
      , parseRules
      , Registry
    ) {
        program._name = path.basename(process.argv[1], '.js').replace('-', ' ');
        program.arguments(exports.command.arguments);
        program.action(function(masters, interpolators) {
            var names = masters.split(',')
              , i;
            console.log(names);
            for(i = 0; i < names.length; i++)
                names[i] = parseArgs.masterName(names[i]);

            var rules = parseRules.fromString(rules, 'InterpolatorArgument', new Registry());

            var project = new MetapolatorProject(io);
            project.load();
            for(i = 0; i < names.length; i++)
                project.open(names[i]);

            console.log('interpolators:', rules);

            project.interpolate(rules);
        });
        program.parse(process.argv);
    }
)}
